use_frameworks!

target 'GDDataDrivenView_Example' do
  pod 'GDDataDrivenView', :path => '../'

  target 'GDDataDrivenView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
